### ISSUE TITLE
How to get schemas list?

### ISSUE THREAD

**Issue by Ciruxx** [ozum/pg-structure#24]
I'm sorry for my english.

Hi!
There is a way to get a schemas name array?

I need to get all tables names in database by schema and i need the name of each schema to do this i should.

Obviusly I was try to use db.schemas, but i get only the public schema or the schema that i pass at pgstructure constructor.

There is another way?

Thanks!

**Comment by ozum** [comment]
I think you want to every schema in a db without giving any schema name to constructor. Right?

```js
await const db = pgStructure({database: 'db', user: 'user', password: 'password'});
const schemas = db.schemas; // public, custom_schema, other_schema... etc.
```

Unfortunately it is not supported, because otherwise all system schemas are included.

## Workaround (NOT TESTED AND NOT SUPPORTED - YOU ARE ON YOUR OWN)

You can edit 5 sql files in sql folder and delete schema related where conditions such as:

```sql
nspname = ANY ($1)  --- DELETE THIS
```

```sql 
udt_schema = ANY($1) --- DELETE THIS
```

etc...

**Comment by Ciruxx** [comment]
Thank you!
