### ISSUE TITLE
Add deferrable/isInitiallyDeferred for constraints

### ISSUE THREAD

**Issue by stephenh** [ozum/pg-structure#89]
Afaict pg-structure has deferrable & isInitiallyDeferred properties for triggers, but not for constraints.

Our app currently depends on deferred FKs, so would be great to have these available in pg-structure, so that we could audit our tables during our build process, to make sure all of our FKs are appropriately deferrable.

Thanks!

**Comment by ozum** [comment]
@stephenh I will add it happily if you could help with SQL where I can get the deferrable & isInitiallyDeferred values for constraints.

**Comment by ozum** [comment]
Hi @stephenh,

The views in `information_schema` is slow to be used, because they join tens of tables. However, it is a good place to start. You can look into the view to see in which table the required column(s) are.

It would be great if you send me the name of the table and columns from there.

Also, you can see a list of all available pg tables from the link below:

https://www.postgresql.org/docs/current/catalogs-overview.html

**Comment by stephenh** [comment]
Ah sure! Looks like they are `condeferrable` and `condeferred`:

https://www.postgresql.org/docs/current/catalog-pg-constraint.html

**Comment by ozum** [comment]
Hi @stephenh, I added `isDeferrable` and `isDeferred` to the constraints.

Could you please check if it is working as expected?

**Comment by stephenh** [comment]
Yep! I pulled down 7.15.0 and it works great; thanks @ozum !

**Comment by ozum** [comment]
@stephenhi, your welcome.
